// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCShMWyaFtdVXWW6JZEm-l0TNAhUbrFlbQ',
    appId: '1:297960666180:web:15f9e4b0752078ca977811',
    messagingSenderId: '297960666180',
    projectId: 'crud-c199e',
    authDomain: 'crud-c199e.firebaseapp.com',
    storageBucket: 'crud-c199e.firebasestorage.app',
    measurementId: 'G-V844RW6RFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm7SBRukZv79zGbf4oOkMcqS0JA1RU1xo',
    appId: '1:297960666180:android:4e4ac98409cf1c30977811',
    messagingSenderId: '297960666180',
    projectId: 'crud-c199e',
    storageBucket: 'crud-c199e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvE4IkDHGtOp4_oJYbhxN3jscObijBcYc',
    appId: '1:297960666180:ios:248bfc9fa21c3bef977811',
    messagingSenderId: '297960666180',
    projectId: 'crud-c199e',
    storageBucket: 'crud-c199e.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvE4IkDHGtOp4_oJYbhxN3jscObijBcYc',
    appId: '1:297960666180:ios:248bfc9fa21c3bef977811',
    messagingSenderId: '297960666180',
    projectId: 'crud-c199e',
    storageBucket: 'crud-c199e.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCShMWyaFtdVXWW6JZEm-l0TNAhUbrFlbQ',
    appId: '1:297960666180:web:70760cc8a1ceb796977811',
    messagingSenderId: '297960666180',
    projectId: 'crud-c199e',
    authDomain: 'crud-c199e.firebaseapp.com',
    storageBucket: 'crud-c199e.firebasestorage.app',
    measurementId: 'G-QR89VN1E9H',
  );
}
